// Copyright (c) 2026 GarudaChain developers
// Distributed under the MIT software license.
//
// GarudaChain hardcoded seed nodes.
//
// Generated by contrib/seeds/generate-seeds.py after initial node deployment.
// Leave empty until mainnet/testnet seed nodes are provisioned.
//
// To add seeds after launch:
//   1. Run seed nodes at seed.garudachain.org, seed2.garudachain.org
//   2. Run contrib/seeds/generate-seeds.py against those nodes
//   3. Replace the arrays below with the generated output

#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H

// Mainnet seeds — populated after mainnet launch
static const uint8_t chainparams_seed_main[] = {};

// Testnet seeds — populated after testnet deployment
static const uint8_t chainparams_seed_test[] = {};

// Testnet4 seeds
static const uint8_t chainparams_seed_testnet4[] = {};

#endif // BITCOIN_CHAINPARAMSSEEDS_H
